### ISSUE TITLE
【编码挑战季】功能实现：重启redis能够重新读 ekg-nebula 数据到redis缓存中

### ISSUE THREAD

**Issue by lightislost** [codefuse-ai/CodeFuse-muAgent#23]
## 问题简述
对于ekg的容器服务中断后，处于redis内存服务的数据会丢失，需要重新丛ekg-nebula图数据库进行重新加载

## 期望产出
一个PR即可

## 能力要求
熟悉python，以及ekg-service代码逻辑

## 预计工作量（每个人日按8小时）
5人日

**Comment by camaze** [comment]
camaze + Please assign this to me

**Comment by lightislost** [comment]
@camaze  Done. Thank you for your willingness to help with this issue!
