### ISSUE TITLE
【编码挑战季】功能完善：NebulaGraph 容器服务启动时初始化

### ISSUE THREAD

**Issue by lightislost** [codefuse-ai/CodeFuse-muAgent#25]
## 问题简述
NebulaGraph 容器服务启动时初始化要等待较长时间，需要进行优化。

## 期望产出
一个PR即可,优化现有功能模块

## 能力要求
熟悉 python 代码，熟悉 Nebula Graph 图数据库

## 预计工作量（每个人日按8小时）
3 人日

**Comment by camaze** [comment]
camaze + please assign this issue to me
