### ISSUE TITLE
调试codechat_example.py一直报错

### ISSUE THREAD

**Issue by busychen** [codefuse-ai/CodeFuse-muAgent#3]
调试codechat_example.py一直报错RuntimeError: Your system has an unsupported version of sqlite3. Chroma   requires sqlite3 >= 3.35.0.  python版本3.10.0. 确定能跑的python版本是多少

**Comment by lightislost** [comment]
是通过conda 虚拟环境上重新pip install codefuse-muagent执行的，还是在原有env上构建的？

**Comment by lightislost** [comment]
暂时没有问题就先关闭了哈，有问题请再打开
