### ISSUE TITLE
【编码挑战季】实现相关的 dal 服务

### ISSUE THREAD

**Issue by lightislost** [codefuse-ai/CodeFuse-muAgent#35]
## 问题简述
当前 tool 等相关配置是在本地通过配置方式存储的，后续需要引入 mysql 数据库，实现相关的 dal 服务，将配置文件落库。

## 期望产出
优化现有的功能模块

## 能力要求
熟悉 mysql，熟悉现有的 tool 逻辑。

## 预计工作量（每个人日按8小时）
3 人日

**Comment by WWP1130** [comment]
WWP1130 Give it to me。～thanks
