### ISSUE TITLE
【编码挑战季】切面生成traceId并在日志中打印

### ISSUE THREAD

**Issue by lightislost** [codefuse-ai/CodeFuse-muAgent#36]
## 问题简述
http接口无traceId逻辑，调试、看日志不方便。需要增加切面生成traceId并在日志中打印出来。

## 期望产出
优化现有的功能模块

## 能力要求
熟悉Java

## 预计工作量（每个人日按8小时）
2人日

**Comment by KUTEJiang** [comment]
KUTEJiang + Please assign this to me
