### ISSUE TITLE
请问是否有进行与dify、metagpt或xagent等项目的定量性能对比？

### ISSUE THREAD

**Issue by CALMCRAZY** [codefuse-ai/CodeFuse-muAgent#48]
例如用基本相同的流程（相关基准测试、谁是卧底这种文本游戏或其它真实用例）测试不同项目的表现。虽然对此框架的知识图谱驱动比较感兴趣，但不知上手难度如何、具体表现如何、是否值得迁移现有工作流。看到相关文章说相比dify固定僵化的任务流更有泛化能力，能进行复杂推理，但具体提升有多少呢？dify集成了大量模型供应商、工具和封装API等等实用功能，优势非常突出，如果muAgent仅仅模糊地说泛化推理更强很难说服别人迁移到这个框架。

**Comment by lightislost** [comment]
目前上手的方式会以本地化启动的方式，然后逐步把功能完善后，开始稳定迭代镜像版本出来

另外，因为整体的逻辑是基于KG+文本的方式来驱动。相较于dify那种固定编排逻辑会有较大的差异。从逻辑上来讲dify的固定工作流会更稳定，但是随着大模型的发展，llm的指令能力进一步提升后，文本驱动的方式会更有优势。

在12月份会发布具体的case展示泛化推理效果。

关于集成大量模型供应商后面可以根据需求慢慢补充，目前支持qwen、openai、零一万物、kimi。

至于其他工具和封装api，我们会逐渐在ui上直接开放工具和agent注册能力，尽可能满足大家的需求。

感谢您的关注！
