### ISSUE TITLE
【编码挑战季】fastapi热启动

### ISSUE THREAD

**Issue by lightislost** [codefuse-ai/CodeFuse-muAgent#52]
## 问题简述
fastapi热启动。当在本地进行测试时，支持本地代码后，服务直接更新成最新代码。不需要反复重启

## 期望产出
一个PR，能够支持热启动

## 能力要求
熟悉fastapi、pyhton

## 预计工作量（每个人日按8小时）
3～5人日

**Comment by camaze** [comment]
camaze + Please assign this to me

**Comment by lightislost** [comment]
@camaze Done. Thank you for your willingness to help with this issue!
