### ISSUE TITLE
提个llmcofig和codesearch的bug

### ISSUE THREAD

**Issue by XingYu-Zhong** [codefuse-ai/CodeFuse-muAgent#70]
![mmexport1730960273248.png](https://github.com/user-attachments/assets/cae7a9fb-6c38-4cf9-bc41-cbac994324e9)

![mmexport1730960270746.png](https://github.com/user-attachments/assets/0e3322c8-12da-481b-a954-c5a481262fd9)

**Comment by lightislost** [comment]
了解，没有兼容langchain导致，一些老逻辑了。

**Comment by XingYu-Zhong** [comment]
这个啥时候发到pip里

**Comment by lightislost** [comment]
如果你要在examples下测试demo的话，可以在py文件里加这么一句话执行本地文件。不过记得环境里不能有muagent这个包，不然会冲突；我再看看有没有其他更新，然后在15号之前更新下。
```python
src_dir = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
```
