### ISSUE TITLE
【BUG】在没有配置llmconfig的时候会去加载环境的baseurl，但是配置后没有按照llmconfig配置的baseurl请求

### ISSUE THREAD

**Issue by XingYu-Zhong** [codefuse-ai/CodeFuse-muAgent#74]
![image](https://github.com/user-attachments/assets/a751b012-fca1-41aa-be82-b9f12b8843c0)

**Comment by lightislost** [comment]
应该是http_client设置的问题，没有兼容api_url的情况导致
