### ISSUE TITLE
离线环境docker-compose模式部署困难

### ISSUE THREAD

**Issue by maco6096** [codefuse-ai/CodeFuse-muAgent#93]
离线环境docker-compose模式部署太困难了， 各种连接外网下载资源，因测试环境外网隔离，很难部署。能提供不需要太多连接外网的版本吗。比如jdk、mvn、muagent-0.1.0-snapshot.jar等等的下载还有yum等安装都预装好的

**Comment by lightislost** [comment]
我们在[codefuse-ai/packages](https://github.com/orgs/codefuse-ai/packages)中提供了对应muagent相关的镜像(beta版本)，有需要可以通过bash docker_pull_images.sh进行下载。如果存在网络问题，可通过[个人阿里云镜像方案](https://github.com/codefuse-ai/CodeFuse-muAgent/blob/main/docs/gh_image_to_aliyun_image.md)完成镜像同步。
